-- 1. Training Model
DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
	NAME VARCHAR (50),
	INT_VALUE INTEGER,
	DOUBLE_VALUE DOUBLE,
	STRING_VALUE VARCHAR (100)
);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('ALGORITHM', 3, NULL, NULL); -- CART
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MODEL_FORMAT', 2, NULL, NULL); -- PMML
INSERT INTO #PAL_PARAMETER_TBL VALUES ('SPLIT_THRESHOLD', NULL, 1e-5, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MIN_RECORDS_OF_PARENT', 2, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MIN_RECORDS_OF_LEAF', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('IS_OUTPUT_RULES', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('IS_OUTPUT_CONFUSION_MATRIX', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('THREAD_RATIO', NULL, 0.4, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('HAS_ID', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('DEPENDENT_VARIABLE', NULL, NULL, 'SPECIES');

DROP TABLE PAL_DT_MODEL_TBL;
CREATE COLUMN TABLE PAL_DT_MODEL_TBL (
	ROW_INDEX INTEGER,
	MODEL_CONTENT NVARCHAR(5000)
);

CALL _SYS_AFL.PAL_DECISION_TREE(IRIS_DATA_TRAIN_TBL, #PAL_PARAMETER_TBL, PAL_DT_MODEL_TBL, ?, ?, ?, ?) WITH OVERVIEW;

-- 2. Scoring Model
DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
	"NAME" VARCHAR (50),
	"INT_VALUE" INTEGER,
	"DOUBLE_VALUE" DOUBLE,
	"STRING_VALUE" VARCHAR (100)
);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('THREAD_NUMBER', 2, null, null);

DROP TABLE PAL_DT_PREDICT_TBL;
CREATE COLUMN TABLE PAL_DT_PREDICT_TBL (
	ID INTEGER,
	SCORE NVARCHAR(100),
	CONFIDENCE DOUBLE
);

CALL _SYS_AFL.PAL_DECISION_TREE_PREDICT (IRIS_DATA_TEST_TBL, PAL_DT_MODEL_TBL, #PAL_PARAMETER_TBL, PAL_DT_PREDICT_TBL) WITH OVERVIEW;

SELECT * FROM PAL_DT_PREDICT_TBL;

SELECT A.*, B.SCORE, B.CONFIDENCE
FROM IRIS_DATA_TEST_TBL A, PAL_DT_PREDICT_TBL B
WHERE A.ID = B.ID
ORDER BY A.ID;
